from collections import defaultdict
from random import choice
from statistics import mean
from typing import List, Dict, Any, Optional, Tuple
import random

from agentboard.agents.vanilla_agent import VanillaAgent
from agentboard.common.registry import registry


# Generated by Copilot
@registry.register_agent("CALMVanillaAgent")
class CALMVanillaAgent(VanillaAgent):
    """CALM-enhanced VanillaAgent that implements CALM's action validation logic."""

    def __init__(self,
                 llm_model: Any,
                 memory_size: int = 100,
                 examples: List[str] = [],
                 instruction: str = "",
                 init_prompt_path: Optional[str] = None,
                 system_message: str = "You are a helpful assistant.",
                 need_goal: bool = False,
                 check_actions: Optional[str] = None,
                 check_inventory: Optional[str] = None,
                 use_parser: bool = True,
                 lm_top_k: int = 30,
                 eps: Optional[float] = None,
                 eps_top_k: int = -1,
                 alpha: float = 0.0) -> None:
        """Initialize CALM vanilla agent with CALM-specific parameters."""
        super().__init__(llm_model, memory_size, examples, instruction, init_prompt_path,
                        system_message, need_goal, check_actions, check_inventory, use_parser)

        # CALM specific attributes
        self.lm_top_k = lm_top_k
        self.eps = eps
        self.eps_top_k = eps_top_k
        self.alpha = alpha
        self.d_in = defaultdict(list)  # Valid actions cache
        self.d_out = defaultdict(list)  # Invalid actions cache
        self.eval_scores = []
        self.max_score = 0

    def run(self, init_prompt_dict: Optional[Dict] = None, valid_actions: Optional[List[str]] = None) -> Tuple[bool, str]:
        """
        Run agent with CALM's action validation logic.

        Args:
            init_prompt_dict: Optional dictionary containing prompt initialization parameters
            valid_actions: List of valid actions for the current state

        Returns:
            Tuple of (success, action)
        """
        # Get base action from vanilla agent
        success, action = super().run(init_prompt_dict)

        if not success or not valid_actions:
            return success, action

        # Apply epsilon-greedy exploration
        if self.eps is not None and random.random() < self.eps:
            if self.eps_top_k > 0:
                valid_subset = valid_actions[:self.eps_top_k]
                action = choice(valid_subset) if valid_subset else action
            else:
                action = choice(valid_actions)

        # Get state key for caching
        state_key = hash(tuple(self.memory[-1][1]))  # Hash current observation
        l_in, l_out = self.d_in[state_key], self.d_out[state_key]

        rej = action not in valid_actions
        actions = valid_actions.copy()

        # Handle rejection using CALM logic
        while rej and len(actions) > 1:
            if action not in l_out:
                l_out.append(action)
            actions.remove(action)
            action = choice(actions)
            rej = action not in valid_actions

        # Update action caches
        if not rej and action not in l_in:
            l_in.append(action)

        if self.use_parser:
            action = self.action_parser_for_special_llms(action)

        return True, action

    def update(self, action: str, state: str, reward: float = 0, score: Optional[float] = None) -> None:
        """
        Update agent state and tracking metrics.

        Args:
            action: Action taken
            state: New state observation
            reward: Reward received
            score: Optional current score
        """
        super().update(action, state)

        if score is not None and score > self.max_score:
            self.max_score = score

        if reward < 0:  # Add negative reward actions to invalid cache
            state_key = hash(tuple(self.memory[-2][1]))  # Get previous state
            if action not in self.d_out[state_key]:
                self.d_out[state_key].append(action)

    @classmethod
    def from_config(cls, llm_model: Any, config: Dict[str, Any]) -> 'CALMVanillaAgent':
        """Create agent instance from config dictionary."""
        base_config = super().from_config(llm_model, config).__dict__
        base_config.update({
            'lm_top_k': config.get('lm_top_k', 30),
            'eps': config.get('eps', None),
            'eps_top_k': config.get('eps_top_k', -1),
            'alpha': config.get('alpha', 0.0)
        })
        return cls(**base_config)
